### ISSUE TITLE
タグ情報を整理して参照しやすくしたい

### ISSUE THREAD

**Issue by ramu** [agile459/agile459.github.com#21]
Issue4の対応によって、旧ウェブサイトより記事を移植したが
ページ上部のメニューの「タグ」「カテゴリ一覧」から参照しやすいように設定されていない
(記事に不要なタグが付いている、タグがついていない記事がある)

タグを付加するルールを定めて、各記事に適切なタグ情報を設定する。

**Comment by kkd** [comment]
当時はJekyllでしたが、タグは使うならシンプルにしたいですね。

「お知らせ」と「レポート」くらいかな。

サイトが変わってもタグを使うならシンプルに倒すのが良いですね。

**Comment by kazweda** [comment]
_posts/ 内のmdファイルですが、
```
description: ""
category: event
tags: [event]
```
大半が上記のようになっています。
tagsは任意で、必要に応じて追加・修正すれば良いと思うのですが、
> 「お知らせ」と「レポート」くらいかな。

これをcategoryとする場合、
`レポート: report`
これは良いとして、
`お知らせ: news`
`お知らせ: info`
`お知らせ: information`
あるいはその他?

ではなくてtagsの整理という意味でしょうか。ちょっと混乱してきました。
