### ISSUE TITLE
Agile459のidobataにゲストがこれるルームを作って公開したい

### ISSUE THREAD

**Issue by kkd** [agile459/agile459.github.com#26]
中で何が行われているか、外にもわかるとよい？参加しやすかったりする？

**Comment by ramu** [comment]
@kkd 現状だとSlack + 勉強会ログで本件だいぶ回ってる印象ありますが、本件どうしますか？

**Comment by kkd** [comment]
賞味期限切れですねー。Slackとログでいいんじゃないでしょうか。closeしますねー。
