### ISSUE TITLE
最新の投稿に日付を追加する？

### ISSUE THREAD

**Issue by kazweda** [agile459/agile459.github.com#40]
最新の投稿がタイトルだけになっていたので、投稿日を追加します。

かつては本文の抜粋も表示されていたようで、今回のJekyllバージョン対応はいろいろと配慮が足りなかったかもしれません。
ただ、今後のサイトの更新をどうするかまだ方針が決まっていないようなので、現時点ではサイトのカスタマイズに手をかけるのは控えています。Jekyllの様子がだんだんと理解できてきた、ということもあります。

**Comment by ramu** [comment]
https://github.com/agile459/agile459.github.com/pull/41 を merge して以下イメージのようになりました

![agile459](https://user-images.githubusercontent.com/148184/52902269-e2c7de80-3251-11e9-93b6-3e1f754af1a9.png)

**Comment by kazweda** [comment]
merge ありがとうございます。
> ReviewersかAssigneesを設定
ですね。了解しました。
