### ISSUE TITLE
「Agile459について」ページの「活動場所」の文言が古い

### ISSUE THREAD

**Issue by ramu** [agile459/agile459.github.com#44]
http://agile459.github.io/about.html

![スクリーンショット 2019-03-13 0 41 41](https://user-images.githubusercontent.com/148184/54214025-d3724300-4528-11e9-8233-97a6c5bfde28.png)

現在は香川でも積極的に活動しており、文言が現状にあっていないように思います

**Comment by kkd** [comment]
@ramu そうですね。

> 四国四県を対象にしており、現在愛媛県、香川県のメンバーを中心に活動をしています。

とでもしましょうか？

**Comment by ramu** [comment]
@kkd 良いと思います！
