### ISSUE TITLE
「アジャイルとは？」ページに "(要追記…)" の文言がある

### ISSUE THREAD

**Issue by ramu** [agile459/agile459.github.com#45]
![スクリーンショット 2019-03-13 0 44 40](https://user-images.githubusercontent.com/148184/54214232-34018000-4529-11e9-9312-4107ce53549f.png)

不要なら削除、必要であれば文言を検討する。

**Comment by kkd** [comment]
更新した。
https://medium.com/agile459/%E3%82%A2%E3%82%B8%E3%83%A3%E3%82%A4%E3%83%AB%E3%81%A8%E3%81%AF-2559eec32318
